let suggestions = [
  'Algorithms',
  'Algorithm types',
  'Algorithms to flowcharts',
  'Algorithms vs Flowcharts',
  'Binary Search',
  'Binary Sort',
  'Binary Tree',
  'Binary Systems',
  'Channel',
  'CodingLab',
  'CodingNepal',
  'YouTube',
  'YouTuber',
  'YouTube Channel',
  'Blogger',
  'Bollywood',
  'Vlogger',
  'Vechiles',
  'Facebook',
  'Freelancer',
  'Facebook Page',
  'Designer',
  'Developer',
  'Web Designer',
  'Web Developer',
  'Personal Computers History',
  'Personal Computer models',
  'Personal Computer or Smartphone ?',
  'Personal Data Security',
  'Login Form in HTML & CSS',
  'Login with one ID',
  'Login with email',
  'Login wikipedia',
  'How to learn HTML & CSS',
  'How to learn JavaScript',
  'How to become Freelancer',
  'How to become Web Designer',
  'How to start Gaming Channel',
  'How to start YouTube Channel from zero',
  'What does HTML stands for?',
  'What does CSS stands for?',
  'What does PHP stands for?',
  'What does SQL stands for?',
];
